name: Branch Deleted
on: delete

jobs:
  job1:
    if: github.event.ref_type == 'branch' && github.event.ref == 'nithesh*'
    runs-on: ubuntu-latest
    steps:
        
    - name: 'Clean up'
      run: echo 'Clean up for branch ${{ github.event.ref }}'
        

