name: Branch Deleted
on: 
  delete:
    branches:    
      - 'nithesh/*'

jobs:
  job1:
    if: github.event.ref_type == 'branch' 
    runs-on: ubuntu-latest
    steps:
        
    - name: 'Clean up'
      run: echo 'Clean up for branch ${{ github.event.ref }}'
        

