name: Branch Deleted
on: delete

jobs:
  job1:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
        
    - name: 'Clean up'
      run: |
            if [[ "${{ github.event.ref }}" == Nithesh_* ]]\ 
            then \
              echo "The variable is greater than 10."\
            fi

    - name: 'Clean up'
      run: echo 'Clean up for branch ${{ github.event.ref }}'
        

