name: Branch Deleted
on: delete

jobs:
  job1:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: 'Clean up'
      run: echo 'Clean up for branch ${{ github.event.ref }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud pubsub topics publish dataform-tbl-cleanup --message=${{ github.event.ref }}'
